name: aralink_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  firebase_messaging: ^15.1.5
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  mailer: ^6.2.0
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1
  firebase_analytics: ^11.3.5
  pointycastle: ^3.9.1
  googleapis_auth: ^1.6.0
  flutter_inappwebview: ^6.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/videos/
    - assets/aralink-d9c4c-87ed3286d716.json