// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuww6gypyEgJAxUC7lZ_WJEz_PRVh1VlU',
    appId: '1:916257358985:web:f1cb9f6f603259b4547258',
    messagingSenderId: '916257358985',
    projectId: 'aralink-d9c4c',
    authDomain: 'aralink-d9c4c.firebaseapp.com',
    storageBucket: 'aralink-d9c4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMEHoPSEd9rJAAB9xeGKQCeUCMyA8iXvo',
    appId: '1:916257358985:android:7003ca12ba5c277b547258',
    messagingSenderId: '916257358985',
    projectId: 'aralink-d9c4c',
    storageBucket: 'aralink-d9c4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxi40OEvrp6kXKWEEFnL4nnJQD5XIc0w8',
    appId: '1:916257358985:ios:83eb9f3e57665fdd547258',
    messagingSenderId: '916257358985',
    projectId: 'aralink-d9c4c',
    storageBucket: 'aralink-d9c4c.appspot.com',
    iosBundleId: 'com.example.aralinkApp',
  );
}
